language: objective-c
osx_image: xcode15.0
xcode_workspace: JSONValue.xcodeproj
xcode_scheme: JSONValue-Package
xcode_sdk: iphonesimulator17.0
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project JSONValue.xcodeproj -scheme JSONValue-Package -sdk iphonesimulator -destination "OS=17.0,name=iPhone 14" ONLY_ACTIVE_ARCH=NO build test
