#if !canImport(ObjectiveC)
import XCTest

extension JSONValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONValueTests = [
        ("test0NumberFalseAndNullHashesAreUnique", test0NumberFalseAndNullHashesAreUnique),
        ("testArrayOfInt8JSONablesProperly", testArrayOfInt8JSONablesProperly),
        ("testArrayOfIntAndFractionalDoubleJSONablesProperly", testArrayOfIntAndFractionalDoubleJSONablesProperly),
        ("testArrayOfIntAndIntegerDoubleLikeIntsJSONablesProperly", testArrayOfIntAndIntegerDoubleLikeIntsJSONablesProperly),
        ("testArrayOfIntJSONablesProperly", testArrayOfIntJSONablesProperly),
        ("testArraySubscripting", testArraySubscripting),
        ("testArrayToFromJSONConvertsProperly", testArrayToFromJSONConvertsProperly),
        ("testCodable", testCodable),
        ("testDecodeToStruct", testDecodeToStruct),
        ("testEarlyNullReturnsNullWhenSubscriptingKeyPath", testEarlyNullReturnsNullWhenSubscriptingKeyPath),
        ("testFalseAndTrueHashesAreNotEqual", testFalseAndTrueHashesAreNotEqual),
        ("testHashesAreConsistent", testHashesAreConsistent),
        ("testJsonBoolCoercesFromNSNumber", testJsonBoolCoercesFromNSNumber),
        ("testJsonBoolCoercesToNSNumber", testJsonBoolCoercesToNSNumber),
        ("testJsonNumberCoercesFromNSNumber", testJsonNumberCoercesFromNSNumber),
        ("testJsonStringCoercesToDouble", testJsonStringCoercesToDouble),
        ("testJsonStringCoercesToInt", testJsonStringCoercesToInt),
        ("testJsonStringCoercesToNSNumber", testJsonStringCoercesToNSNumber),
        ("testJsonStringToNSDate", testJsonStringToNSDate),
        ("testMissingDataFailsDecoding", testMissingDataFailsDecoding),
        ("testPrintingJsonNumberAsFraction", testPrintingJsonNumberAsFraction),
        ("testPrintingJsonNumberAsInt", testPrintingJsonNumberAsInt),
        ("testsEncodeAsString", testsEncodeAsString),
        ("testSubscriptingReturnsNilIfAttributeIsNonExistent", testSubscriptingReturnsNilIfAttributeIsNonExistent),
        ("testSubscriptingWithDotsUsesComponentsForTraversal", testSubscriptingWithDotsUsesComponentsForTraversal),
        ("testSubscriptingWithDotsUsesWholeStringIfComponentsFail", testSubscriptingWithDotsUsesWholeStringIfComponentsFail),
        ("testUniqueHashesForJSONArrayReordering", testUniqueHashesForJSONArrayReordering),
        ("testUniqueHashesForKeyValueReorderingOnJSONObject", testUniqueHashesForKeyValueReorderingOnJSONObject),
    ]
}

extension UtilitiesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilitiesTests = [
        ("testAsJsonNumber", testAsJsonNumber),
        ("testIsBool", testIsBool),
        ("testIsReal", testIsReal),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONValueTests.__allTests__JSONValueTests),
        testCase(UtilitiesTests.__allTests__UtilitiesTests),
    ]
}
#endif
